# This workflow runs on changes to the `sql/` directory.
# It auto-generates:
# - README.md files for each directory containing SQL scripts
# - _runlist.txt files for each SQL folder
# 
# Can also be triggered manually via workflow_dispatch.

name: Generate README and _runlist

on:
  push:
    paths:
      - 'sql/**'  # Trigger on changes to the 'sql' directory and its subdirectories
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the Python version

      # Install dependencies (if needed)
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyyaml  
          pip install chardet 

      # Run the Python script
      - name: Generate README
        run: python _lib/generate_readmes.py

      - name: Generate _runlist.txt
        run: python _lib/handle_generate_runlist.py

      # Commit and push changes to README.md
      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update README with SQL scripts" || echo "No changes to commit"
          git push
